version: "3.9"

services:
  backend:
    build:
      context: ./bike-api
      dockerfile: Dockerfile.dev
    container_name: bike-api
    ports:
      - "8080:8080"
    volumes:
      - ./bike-api:/app
    environment:
      SPRING_DOCKER_COMPOSE_ENABLED: false
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/uge_bike
      SPRING_DATASOURCE_USERNAME: uge
      SPRING_DATASOURCE_PASSWORD: uge

      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_USERNAME: ""
      SPRING_MAIL_PASSWORD: ""
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"
    depends_on:
      - postgres
      - mailhog
    command: mvn spring-boot:run

  frontend:
    build:
      context: ./bike-frontend
      dockerfile: Dockerfile.dev
    container_name: bike-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./bike-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: ng serve --host 0.0.0.0 --poll=2000

  postgres:
    image: postgres:16
    container_name: uge_bike
    environment:
      POSTGRES_DB: uge_bike
      POSTGRES_USER: uge
      POSTGRES_PASSWORD: uge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
