services:
  postgres:
    image: postgres:16
    container_name: uge_bike
    environment:
      POSTGRES_DB: uge_bike
      POSTGRES_USER: uge
      POSTGRES_PASSWORD: uge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
    # optional, only if you want persistence (usually not needed)
    # volumes:
    #   - mailhog_data:/home/mailhog

volumes:
  postgres_data:
  # mailhog_data:
